### ISSUE TITLE
**Definir API web**

### ISSUE THREAD

**Issue by miguescri** [UNIZAR-30226-2018-05/Back-end#2]
Especificar qué recursos individuales va a proveer el servidor y qué peticiones REST dan lugar a qué respuestas.

Ejemplos: 
- Endpoint que, dado un identiifcador de usuario, devuelve la lista de identificadores (o puede que algo más de información escrita para evitar problemas de latencia) de las canciones favoritas.
- Endpoint que, dado un identificador de canción, devuelve una imagen png de la carátula.
...

**Comment by miguescri** [comment]
He creado el pull request #5 para que comentéis lo que veáis necesario sobre mi propuesta de API.

**Comment by miguescri** [comment]
La definición de la API se hizo ajustándos a los requisitos descritos en el documento técnico entregado el 2 de marzo al cliente. 

Puesto que parece que dichos requisitos eran incompletos, por favor, **añadid a continuación los requisitos que finalmente decidáis incluir en la nueva versión del documento**.

**Comment by robertoccu** [comment]
Cosas a añadir (y deberá añadirse a los requisitos del documento):

Canción:
- Debe tener album
- Debe tener una imagen (carátula)

Album:
- Es una lista de canciones
- Tiene una imagen (carátula)
- Tiene unos artistas
- Tiene un nombre
- Tiene una fecha de salida

Playlist (y cualquier lista de canciones)
- Tiene una fecha de creación

___________

Cosas que no estaban en los requisitos pero están en la API (no hace falta quitarlo, va bien, se añadirán a requisitos):

Usuario:
- Biografía
- Nombre completo

**Comment by miguescri** [comment]
¿Quién puede definir álbunes?

**Comment by miguescri** [comment]
¿Los artistas de un álbum son la unión de los artistas de las canciones individuales?

**Comment by robertoccu** [comment]
Acabo de darme cuenta de que falta algo esencial en la API: Los artistas. Estos tienen canciones, foto, información (bio) y álbumes. Será necesario buscar por ellos en el futuro, podrás ver los artistas de tus canciones en una página y cada uno tendrá su página, diferente a la de un usuario para mostrar más información.

No se si te sirve esto como definición de álbumes: Un álbum es una lista de canciones con un artista como autor (solo uno, basado en Spotify) que pertece al repertorio de éste.

**Comment by miguescri** [comment]
Recibido.

*Miguel Escribano*

**Comment by miguescri** [comment]
Es necesario dotar de la posibilidad de recibir los audios por streamming.
