### ISSUE TITLE
Tipo inválido en canciones en llamada a /profile/{profileID}

### ISSUE THREAD

**Issue by robertoccu** [UNIZAR-30226-2018-05/Back-end#21]
Al realizar la llamada a /profile/{profileID} con ID = "1" (el perfil ya creado para pruebas), el género de las canciones se devuelve como String en vez de como Array de Strings que es lo que indica la especificación.

Lo que se devuelve:
 "genre": "pop",

Lo que se espera:
"genre": [
            "rock",
            "rock"
          ],

Commit 1c4c860

**Comment by jorgeRambla** [comment]
Solucionado en el commit 4359013
