### ISSUE TITLE
Autentificación alternativa a Cookies

### ISSUE THREAD

**Issue by robertoccu** [UNIZAR-30226-2018-05/Back-end#22]
En Modelo tenemos problemas con la autentificación por Cookies, pues el código autogenerado por Swagger para Java no parece incorporar ninguna manera de guardar las Cookies que recibe.

Editar este código, sobre todo en la versión de JavaScript nos sería bastante complicado y rompería la modularidad al no poder reemplazarlo por una nueva versión de la especificación de la API en caso de haberla. Tampoco sobra el tiempo.

¿Habría alguna forma alternativa?

**Comment by miguescri** [comment]
Por favor, prueba con la primera solución de este post cambiando lo que
indica el usuario LETS en un comentario:
https://stackoverflow.com/questions/24263921/how-to-implement-cookie-handling-on-android-using-okhttp#34746219

Habría que aplicarlo en el fichero ApiClient.java en el constructor, donde
se asigna un OkHttpClient vacío.


*Miguel Escribano*

2018-05-17 18:05 GMT+02:00 robertoccu <notifications@github.com>:

**Comment by robertoccu** [comment]
La versión de OkHttp que utiliza el código de Swagger para Java es la 2.7.5. La solución que comentas es para OkHttp3 (3.0.0+).

**Comment by miguescri** [comment]
Entonces prueba la segunda respuesta.

**Comment by robertoccu** [comment]
Ostris, debería haber probado a bajar más; las prisas... 

He probado la segunda respuesta y funciona en la capa de modelo. A lo largo del fin de semana probaré en Android para asegurarme de que el sistema no se las carga.

**Comment by miguescri** [comment]
Niiice

**Comment by robertoccu** [comment]
Tras una prueba rápida registrando una cuenta, logueandose y luego cerrando sesión no ha dado error así que parece ser que está todo bien. Cierro el issue y si encontramos algún problema relacionado con las Cookies os lo hacemos saber.
