### ISSUE TITLE
Sesiones y enviar datos al servidor

### ISSUE THREAD

**Issue by robertoccu** [UNIZAR-30226-2018-05/Back-end#3]
Desde @UNIZAR-30226-2018-05/modelo hemos pensado en enviar al servidor con cada petición una ID de Sesión aleatoria y única asignada a un usuario en un dispositivo en el servidor que permita autentificar cada petición. ¿Qué os parece? ¿Alguna mejor solución?

Por otra parte tenemos dudas de como tendremos que enviar las cosas al servidor, por ejemplo el cambio de una contraseña, el login, añadir un amigo a un usuario, etc....

;)

**Comment by miguescri** [comment]
Todo el tema de la autentificación de usuario se hará desde el server a través de cookies de sesión firmadas que irán en la cabecera de los paquetes (automatizado con las herramientas de sesión de Flask).

Para cada una de las operaciones que mencionas va a haber un endpoint específico de API, no os preocupéis.

**Comment by robertoccu** [comment]
Pero en Android no hay cookies. Para que se tenga en cuenta.

**Comment by miguescri** [comment]
Entiendo que te refieres que no hay un almacén de cookies por defecto, pero cookies hay, ya que son parte del HTTP. Debería haber una manera sencilla de conservar las cookies del header del mensaje recibido del server hasta que tengas que hacer alguna petición con autentificación; lo miraré.

De todas formas, en caso de que no lo hubiera, ese tipo de tickets de sesión se generan siempre desde el servidor por motivos de seguridad.
